definitions:
  auth.User:
    properties:
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  comments.Comment:
    properties:
      author:
        type: string
      authorId:
        type: integer
      created:
        type: string
      id:
        type: integer
      postId:
        type: integer
      text:
        type: string
    type: object
  images.Image:
    properties:
      authorId:
        type: integer
      created:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  posts.Post:
    properties:
      author:
        type: string
      authorId:
        type: integer
      comments:
        type: integer
      created:
        type: string
      id:
        type: integer
      likes:
        type: integer
      tags:
        items:
          $ref: '#/definitions/tags.Tag'
        type: array
      text:
        type: string
      title:
        type: string
    type: object
  posts.Posts:
    properties:
      nposts:
        type: integer
      posts:
        items:
          $ref: '#/definitions/posts.Post'
        type: array
    type: object
  tags.Tag:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.User'
      responses:
        "200":
          description: OK
        "400":
          description: Invalid Request
        "405":
          description: Method Not Allowed
        "409":
          description: User Already Exists
        "500":
          description: Internal Error
      summary: register a new user
      tags:
      - auth
  /api/auth/token:
    get:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Invalid Password
        "404":
          description: User Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Erorr
      summary: Get auth token for the user
      tags:
      - auth
  /api/comments/{id}:
    delete:
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Token
        "403":
          description: No Access To Comment
        "404":
          description: Comment Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Delete the comment
      tags:
      - comments
    get:
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comments.Comment'
        "400":
          description: Bad Request
        "404":
          description: Comment Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Get the comment by ID
      tags:
      - comments
    post:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/comments.Comment'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Header
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
      summary: Add a comment to the post
      tags:
      - comments
    put:
      consumes:
      - application/json
      parameters:
      - description: Comment ID
        in: path
        name: id
        required: true
        type: integer
      - description: Comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/comments.Comment'
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Token
        "403":
          description: No Access To Comment
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Update the comment
      tags:
      - comments
  /api/images/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/images.Image'
            type: array
        "404":
          description: Images Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Get images
      tags:
      - images
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Image File
        in: formData
        name: image
        required: true
        type: file
      - description: Auth Header
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Token
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Upload an image
      tags:
      - images
  /api/images/{id}:
    delete:
      parameters:
      - description: Image ID
        in: path
        name: id
        required: true
        type: integer
      - description: Auth Header
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Token
        "403":
          description: No Access To Image
        "404":
          description: Image Not Found
        "500":
          description: Internal Error
      summary: Delete Image
      tags:
      - images
    get:
      parameters:
      - description: Image ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/images.Image'
        "400":
          description: Bad Request
        "500":
          description: Internal Error
      summary: Get Image by ID
      tags:
      - images
  /api/posts/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/posts.Post'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Posts Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Get post list
      tags:
      - posts
    post:
      consumes:
      - application/json
      parameters:
      - description: Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/posts.Post'
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Header
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Add a new post
      tags:
      - posts
  /api/posts/{id}:
    delete:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Token
        "403":
          description: No Access To Post
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Delete a post
      tags:
      - posts
    get:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/posts.Post'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Get a post by ID
      tags:
      - posts
    put:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/posts.Post'
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Token
        "403":
          description: No Access To Post
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Update a post
      tags:
      - posts
  /api/posts/{id}/comments:
    get:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/comments.Comment'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Comments Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Get comments for the post
      tags:
      - comments
  /api/posts/{id}/dislike:
    post:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Header
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Dislike a post
      tags:
      - posts
  /api/posts/{id}/like:
    post:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Auth Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Invalid Auth Header
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Like a post
      tags:
      - posts
  /api/posts/{id}/likes:
    get:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "404":
          description: Post Not Found
        "500":
          description: Internal Error
      summary: Get likes for the post
      tags:
      - posts
  /api/posts/{id}/tags:
    get:
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tags.Tag'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Get all tags for the post
      tags:
      - tags
  /api/posts/search/q/{query}:
    get:
      parameters:
      - description: Query
        in: path
        name: query
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/posts.Post'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Post Not Found
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Error
      summary: Search posts by title
      tags:
      - posts
  /api/posts/tagPosts/t/{name}:
    get:
      parameters:
      - description: Tag Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/posts.Posts'
        "400":
          description: Bad Request
        "404":
          description: Tag Not Found
        "500":
          description: Internal Error
      summary: Get posts associated with the tagPosts
      tags:
      - tags
swagger: "2.0"
